---
- name: Install Java 1.8 and basic dependencies
  apt: 
    name: "{{ item }}"
    update_cache: yes 
    state: present
  loop:
    - unzip
    - openjdk-8-jdk

- name: Download Wildfly from jboss.org
  get_url: 
    url: http://download.jboss.org/wildfly/13.0.0.Final/wildfly-13.0.0.Final.zip 
    dest: /opt/wildfly-13.0.0.Final.zip

- name: Create base directory for Wildfly
  file:
    path: "{{ base_dir }}"
    state: directory
    mode: '0755'

- name: Extract binary archive
  unarchive:
    dest: "{{ base_dir }}"
    src: /opt/wildfly-13.0.0.Final.zip
    creates: "{{ wildfly_home }}"
    copy: no

- name: Rename install directory
  command: /bin/mv wildfly-13.0.0.Final wildfly 
  args:
    chdir: "{{ base_dir }}" 
    creates: "{{ wildfly_home }}"

- name: Copying standalone.xml configuration file
  template:
    src: standalone.xml.j2
    dest: "{{ wildfly_home }}/standalone/configuration/"
  
- name: Add group "jboss"
  group: 
    name: jboss

- name: Add user "jboss"
  user: 
    name: jboss 
    group: jboss 
    home: "{{ wildfly_home }}"

- name: Change ownership of Wildfly installation
  file: 
    path: "{{ wildfly_home }}"
    owner: jboss 
    group: jboss
    state: directory 
    recurse: yes

- name: Run Wildfly server in standalone mode
  shell: nohup /opt/jboss/wildfly/bin/standalone.sh &
