# Setting host
- hosts: localhost
  gather_facts: false
#Variables
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    app_name: eap72
# Pre-Tasks to validate if Minikube is running
  pre_tasks:
    - name: Check Minikube's status.
      command: minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true
  # Check existing deployment manifest
  tasks:
    - name: Get existing deployment name.
      shell: kubectl get deployment {{ app_name }} -o NAME
      register: deployment_name
  # Delete deployment manifest if found.
    - name: Delete deployment if found.
      shell: |
        kubectl delete deployment {{ app_name }}
      when: deployment_name.stdout.find('eap72') != -1
  # Check for existing service object 
    - name: Get existing service name.
      shell: kubectl get svc {{ app_name }} -o NAME
      register: svc_name
  # Delete service if found.
    - name: Delete service if found.
      shell: |
        kubectl delete svc {{ app_name }}
      when: svc_name.stdout.find('eap72') != -1